// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNysoaJdPzlhjCi00bhqiS3b6yWV14JY',
    appId: '1:740713092958:web:0dadd7021e019308d061cf',
    messagingSenderId: '740713092958',
    projectId: 'todo-1412a',
    authDomain: 'todo-1412a.firebaseapp.com',
    storageBucket: 'todo-1412a.appspot.com',
    measurementId: 'G-EMF6FJRJHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXaAdgq3OE1a9yYyYF-zFGO4-GBktzLko',
    appId: '1:740713092958:android:39e5f6dd0d9c2e98d061cf',
    messagingSenderId: '740713092958',
    projectId: 'todo-1412a',
    storageBucket: 'todo-1412a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScaQ8qQWPr7ZyoyrfOo5kAuAb9wORouE',
    appId: '1:740713092958:ios:c07b3b1b8d1fb1b7d061cf',
    messagingSenderId: '740713092958',
    projectId: 'todo-1412a',
    storageBucket: 'todo-1412a.appspot.com',
    iosClientId: '740713092958-dk8hg7a9qtecr3rplpqkjh014k693n63.apps.googleusercontent.com',
    iosBundleId: 'com.example.todotodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDScaQ8qQWPr7ZyoyrfOo5kAuAb9wORouE',
    appId: '1:740713092958:ios:c07b3b1b8d1fb1b7d061cf',
    messagingSenderId: '740713092958',
    projectId: 'todo-1412a',
    storageBucket: 'todo-1412a.appspot.com',
    iosClientId: '740713092958-dk8hg7a9qtecr3rplpqkjh014k693n63.apps.googleusercontent.com',
    iosBundleId: 'com.example.todotodo',
  );
}
